version: '2'

services:
  workspace:
    image: node
    volumes:
      - "./:/www"
    working_dir: /www
    ports:
      - "8381:8080"
    tty: true

  # server:
  #   image: khhdocker/nginx-phpfpm:2.0
  #   environment:
  #     WEBROOT: '/var/www/dist'
  #     PROROOT: '/var/www'
  #   volumes:
  #     - ./:/var/www
  #   ports:
  #     - "8382:80"
